edu_crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView, LogoutView 

app_name = 'main'

urlpatterns = [
    # user login
    path("login/", LoginView.as_view(template_name='login.html'), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("", HomeView.as_view(), name="home"),
    # teacher
    path("update_teacher/<pk>", TeacherUpdateView.as_view(), name="update_teacher"),
    path("delete_teacher/<pk>", TeacherDeleteView.as_view(), name="delete_teacher"),
    path("add_teacher/", TeacherCreateView.as_view(), name="add_teacher"),
    path("teachers/", TeachersView.as_view(), name="teachers"),
    path("pay_for_teacher/", pay_for_teacher, name="forteacher"),
    # students
    path("delete_student/<pk>", StudentDeleteView.as_view(), name="delete_student"),
    path("update_student/<pk>", StudentUpdateView.as_view(), name="update_student"),
    path("add_student/", create_student, name="add_student"),
    path("students/", StudentsView.as_view(), name="students"),
    path("student/<pk>", student_detail, name="student"),
    path("get_plus/", get_plus, name="get_plus"),
    path("pay/", pay, name="pay"),
    # groups
    path("delete_group/<pk>", GroupDeleteView.as_view(), name="delete_group"),
    path("update_group/<pk>", GroupUpdateView.as_view(), name="update_group"),
    path("groups/", GroupsView.as_view(), name="groups"),
    path("add_group/", create_group, name="add_group"),
    path("group/<pk>", group_detail, name="group"),
    path("history_group/<pk>", group_history, name="group_history"),
    path("new_groups/", NewGroupsView.as_view(), name="new_groups"),

    path("add_subject/", add_subject, name="add_subject"),
    path("add_camewith/", add_camewith, name="add_camewith"),
    path("brithdays/", brithdays, name="brithday"),
    path("call/", call, name="call"),
    path("active_group/<pk>", active_group, name="activate"),
]   

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Subjects(models.Model):
    name = models.CharField("Fan nomi", max_length=150)
    
    def __str__(self):
        return self.name


class CameWith(models.Model):
    name = models.CharField("Sabab nomi", max_length=250)

    def __str__(self):
        return self.name

class Teacher(models.Model):
    user = models.ForeignKey(User, related_name="teacher", on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField("Ismi", max_length=150)
    surname = models.CharField("Familiyasi", max_length=150)
    image = models.ImageField("O'qituvchi rasmi", upload_to='teacher_img/',null=True, blank=True)
    tel_num = models.CharField("Telefon raqami", max_length=50, blank=True)
    subject = models.ForeignKey(Subjects, related_name="teachers", on_delete=models.PROTECT)
    price = models.PositiveIntegerField("Bitta dars uchun narx", default=0)
    # harajatlar hisobi
    countsub = models.PositiveIntegerField("Bir oydagi darslar soni", default=0)
    allprice = models.PositiveIntegerField("Jami maosh", default=0)

    def __str__(self):
        return f"{self.name} {self.surname}"


class Group(models.Model):
    own = models.ForeignKey(User, related_name="own_group", on_delete=models.CASCADE, blank=True, null=True)
    teacher = models.ForeignKey(Teacher, related_name="group", on_delete=models.CASCADE, blank=True)
    name = models.CharField("Guruh nomi", max_length=350)
    subject = models.ForeignKey(Subjects, related_name="teachers_group", on_delete=models.CASCADE, blank=True)
    time = models.CharField("Vaqti", max_length=50)
    kunlari = models.CharField("Hafta kunlari", max_length=350)
    payment = models.PositiveIntegerField("To'lov", default=0)
    days_in_month = models.PositiveIntegerField("Kun soni", default=0)

    active = models.BooleanField("aktiv/aktiv emas", default=False)
    
    def __str__(self):
        if self.active == True:
            return self.name
        else:
            return f"{self.name} (Qabuldagi guruh)"


class Student(models.Model):
    own = models.ForeignKey(User, related_name="students", on_delete=models.CASCADE, blank=True, null=True)
    group = models.ForeignKey(Group, related_name="student", on_delete=models.CASCADE, blank=True, null=True)
    # shaxsiy ma'lumotlari
    name = models.CharField("Ismi", max_length=150)
    surname = models.CharField("Familiyasi", max_length=150)
    brith = models.CharField("Tug'ulgan sanasi", max_length=50)
    image = models.ImageField("O'quvchi rasmi", upload_to='student_img/', blank=True, null=True)
    password_img = models.ImageField("Pasort rasmi", upload_to='students_passport', blank=True)
    tel_num = models.CharField("Telefon raqami", max_length=50, blank=True)
    place = models.CharField("Yashash manzili", max_length=50)
    # harajatlar hisobi
    price = models.PositiveIntegerField("Chegirma",default=0)
    countsub = models.PositiveIntegerField("Bir oydagi darslar soni",default=0)
    allprice = models.PositiveIntegerField("Jami to'lov",default=0)

    called = models.BooleanField("called/not called",default=False)
    camewith = models.ForeignKey(CameWith, related_name="students", blank=True, on_delete=models.PROTECT)
        
    def __str__(self):
        return self.name


class CameHistory(models.Model):
    student = models.ForeignKey(Student, related_name="history", on_delete=models.CASCADE)
    time = models.CharField("Kelgan sanasi", blank=True, max_length=100)
    came = models.BooleanField("keldi/kelmadi", default=False)
    apset = models.BooleanField("sababli/sababsiz", default=False)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.student.name


class PayedHistory(models.Model):
    student = models.ForeignKey(Student, related_name="payment", on_delete=models.CASCADE)
    time = models.CharField("To'lagan sanasi", blank=True, max_length=100)
    payed = models.PositiveIntegerField("summasi", default=0)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.student.name
    

class TeacherHistory(models.Model):
    teacher = models.ForeignKey(Teacher, related_name="history", on_delete=models.CASCADE)
    time = models.CharField("to'langan vaqt", blank=True, max_length=150)
    price = models.PositiveIntegerField("to'langan summa", default=0)

    def __str__(self):
        return self.teacher.name

    

templates/login.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSS-->
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script src="/static/js/jquery-2.1.4.min.js"></script>
    <title>Vali Admin</title>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries-->
    <!--if lt IE 9
    script(src='https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js')
    script(src='https://oss.maxcdn.com/libs/respond./static/js/1.4.2/respond.min.js')
    -->
  </head>
  <body>
    <section class="material-half-bg">
      <div class="cover"></div>
    </section>
    <section class="login-content">
      <div class="login-box">
        <form class="login-form" method="POST">
            {% csrf_token %}
          <h3 class="login-head"><i class="fa fa-lg fa-fw fa-user"></i>KIRISH</h3>
          <div class="form-group">
            <label class="control-label">USERNAME</label>
            <input class="form-control" name="username" type="text" placeholder="Email" autofocus>
          </div>
          <div class="form-group">
            <label class="control-label">PASSWORD</label>
            <input class="form-control" name="password" type="password" placeholder="Password">
          </div>
          <div class="form-group btn-container">
            <button type="submit" class="btn btn-primary">TASDIQLASH <i class="fa fa-sign-in fa-lg"></i></button>
          </div>
        </form>
      </div>
    </section>
  </body>
  
  <script src="/static/js/bootstrap.min.js"></script>
  <script src="/static/js/plugins/pace.min.js"></script>
  <script src="/static/js/main.js"></script>
</html>

templates/update_group.html
{% extends 'wrapper.html' %}
{% load static %}

{% block content %}
<div class="content-wrapper">
<div class="row">
    <div class="col-md-7">
        <form method="POST" class="form-horizontal" enctype="multipart/form-data">{% csrf_token %}
            <div class="card">
                <h3 class="card-title">Guruhni yangilash</h3>
                <div class="card-body">
                    <div class="form-group">
                        <label class="control-label col-md-3">Nomi</label>
                        <div class="col-md-8">
                            <input value="{{form.name.value}}" name="name" class="form-control" type="text" placeholder="Nomini yozing">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">Fani</label>
                        <div class="col-md-8">
                            {{form.subject}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">Kunlari</label>
                        <div class="col-md-8">
                            <input value="{{form.kunlari.value}}" name="kunlari" class="form-control" placeholder="Qaysi kunlarda bo'lishini yozing">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">Vaqti</label>
                        <div class="col-md-8">
                            <input name="time" value="{{form.time.value}}" class="form-control" placeholder="13:00-15:00">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">Bir oylik to'lov</label>
                        <div class="col-md-8">
                            <input value="{{form.payment.value}}" name="payment" type="number" class="form-control" placeholder="Bir oylik to'lovini yozing">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">Bir oyda nechta dars</label>
                        <div class="col-md-8">
                            <input value="{{form.days_in_month.value}}" name="days_in_month" type="number" class="form-control" placeholder="Qaysi kunlarda bo'lishini yozing">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">O'qituvchini tanlang</label>
                        <div class="col-md-8">
                            {{form.teacher}} 
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-3">
                            <button class="btn btn-primary icon-btn" type="submit"><i class="fa fa-fw fa-lg fa-check-circle"></i>TASDIQLASH</button>
                            <a class="btn btn-default icon-btn" href="{% url 'main:home' %}"><i class="fa fa-fw fa-lg fa-times-circle"></i>BEKOR QILISH</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-5">
        <img style="width: 100%;" class="card" src="/static/images/group.jpg" alt="">
    </div>
</div>
</div>
<script>
    $("#id_teacher").addClass('form-control')
    $("#id_subject").addClass('form-control')
</script>
{% endblock content %}

templates/update_student.html
{% extends 'wrapper.html' %}
{% load static %}

{% block content %}
<div class="content-wrapper">
<div class="row">
    <div class="col-md-7">
        <form method="POST" class="form-horizontal" enctype="multipart/form-data">{% csrf_token %}
            <div class="card">
                <h3 class="card-title">O'quvchi Qo'shish</h3>
                <div class="card-body">
                    <div class="form-group">
                        <label class="control-label col-md-3">Ismi</label>
                        <div class="col-md-8">
                            <input value="{{form.name.value}}" name="name" class="form-control" type="text" placeholder="Ismini yozing">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">Familiya</label>
                        <div class="col-md-8">
                            <input value="{{form.surname.value}}" name="surname" class="form-control col-md-8" type="text" placeholder="Familiyasini yozing">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">Tug'ilgan sanasi</label>
                        <div class="col-md-8">
                            <input value="{{form.brith.value}}" name="brith" class="form-control col-md-8" type="date" placeholder="Familiyasini yozing">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">Yashash joyi</label>
                        <div class="col-md-8">
                            <input value="{{form.place.value}}" name="place" class="form-control" placeholder="Yashash manzilini yozing">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">Tel. raqami</label>
                        <div class="col-md-8">
                            <input value="{{form.tel_num.value}}" name="tel_num" class="form-control col-md-8" type="number" placeholder="99 999 99 99">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">Rasmini tanlang</label>
                        <div class="col-md-8">
                            
                            {% if form.image.value %}
                            <a href="{{form.image.value.url}}" class="label label-success">Hozirgini ko'rish</a>
                            {% endif %}
                                
                            <input value="" name="image" class="form-control" type="file">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">Guruhni tanlang</label>
                        <div class="col-md-8">
                            {{form.group}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">Chegirma</label>
                        <div class="col-md-8">
                            <input value="{{form.price.value}}" name="price" class="form-control col-md-8" type="number" placeholder="Chegirma pulini yozing">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">Markazimizni qayerdan topdi?</label>
                        <div class="col-md-8">
                            {{form.camewith}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">Passport rasmi</label>
                        <div class="col-md-8">
                            {% if form.image.value %}
                            <a href="{{form.password_img.value.url}}" class="label label-success">Hozirgini ko'rish</a>
                            {% endif %}
                                
                            <input name="password_img" class="form-control" type="file">
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-3">
                            <button class="btn btn-primary icon-btn" type="submit"><i class="fa fa-fw fa-lg fa-check-circle"></i>Tasdiqlash</button>
                            <a class="btn btn-default icon-btn" href="{% url 'main:home' %}"><i class="fa fa-fw fa-lg fa-times-circle"></i>Bekor qilish</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-5">
        <img style="width: 100%;" class="card" src="/static/images/student.jpg" alt="">
    </div>
</div>
</div>
<script>
    $('input').addClass('form-control')
    $('#id_group').addClass('form-control')
    $('#id_camewith').addClass('form-control')
</script>
{% endblock content %}

templates/wrapper.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="initial-scale=1">
    <!-- CSS-->
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script src="/static/js/jquery-2.1.4.min.js"></script>
    <title>Vali Admin</title>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries-->
    <!--if lt IE 9
    script(src='https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js')
    script(src='https://oss.maxcdn.com/libs/respond./static/js/1.4.2/respond.min.js')
    -->
  </head>
  <body class="sidebar-mini fixed">
    <div class="wrapper">
      <!-- Navbar-->
      <header class="main-header hidden-print">
        <a class="logo" href="{% url 'main:home' %}"><img src="/static/images/logo.jpg" alt=""> Alfa</a>
        <nav class="navbar navbar-static-top">
          <!-- Sidebar toggle button--><a class="sidebar-toggle" href="#" data-toggle="offcanvas"></a>
          <!-- Navbar Right Menu-->
          <div class="navbar-custom-menu">
            <ul class="top-nav">
              <!-- User Menu-->
              <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-plus fa-lg"></i> Fan</a>
                <ul class="dropdown-menu settings-menu">
                  <li>
                    <form action="{% url 'main:add_subject' %}" method="GET">
                      <input type="text" class="form-control" placeholder="Fanni nomini yozing" name="name">
                      <button type="submit" class="btn btn-primary">Qo'shish</button>
                    </form>  
                  </li>
                </ul>
              </li>
              <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-plus fa-lg"></i> Sabab</a>
                <ul class="dropdown-menu settings-menu">
                  <li>
                    <form action="{% url 'main:add_camewith' %}" method="GET">
                      <input type="text" class="form-control" placeholder="Sababni yozing" name="name">
                      <button type="submit" class="btn btn-primary">Qo'shish</button>
                    </form>  
                  </li>
                </ul>
              </li>
              <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-plus fa-lg"></i></a>
                <ul class="dropdown-menu settings-menu">
                  <li><a href="{% url 'main:add_teacher' %}"><i class="fa fa-plus fa-lg"></i> O'qituvchi</a></li>
                  <li><a href="{% url 'main:add_group' %}"><i class="fa fa-plus fa-lg"></i> Guruh</a></li>
                  <li><a href="{% url 'main:add_student' %}"><i class="fa fa-plus fa-lg"></i> O'quvchi</a></li>
                </ul>
              </li>
              <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user fa-lg"></i></a>
                <ul class="dropdown-menu settings-menu">
                  <li><a href="{% url 'main:logout' %}"><i class="fa fa-sign-out fa-lg"></i> Chiqish</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <!-- Side-Nav-->
      <aside class="main-sidebar hidden-print">
        <section class="sidebar">
          <!-- Sidebar Menu-->
          <ul class="sidebar-menu">
            <li class=""><a href="{% url 'main:home' %}"><i class="fa fa-home"></i><span>Bosh sahifa</span></a></li>
            <li><a href="{% url 'main:students' %}"><i class="fa fa-graduation-cap"></i><span> O'quvchilar</span></a></li>
            <li><a href="{% url 'main:teachers' %}"><i class="fa fa-user-secret"></i><span> O'qituvchilar</span></a></li>
            <li><a href="{% url 'main:groups' %}"><i class="fa fa-list"></i><span> Guruhlar</span></a></li>
            <li><a href="{% url 'main:new_groups' %}"><i class="fa fa-tasks"></i><span> Qabul</span></a></li>
            <li><a href="{% url 'main:brithday' %}"><i class="fa fa-birthday-cake"></i><span> Tug'ilgan kunlar</span></a></li>
            <li><a href="{% url 'main:faq' %}"><i class="fa fa-flag"></i><span> O'qib chiqish shart</span></a></li>
          </ul>
        </section>
      </aside>
{% block content %}
    
{% endblock content %}

<style>
  @media (max-width: 770px) {
    .desktop{
        display: none;
    }
}
  @media (min-width: 770px) {
    .mobile{
        display: none;
    }
}
</style>

    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/plugins/pace.min.js"></script>
    <script src="/static/js/main.js"></script>
  </body>
</html>